### ISSUE TITLE
Update to Godot 4

### ISSUE THREAD

**Issue by ThePat02** [vyshliy/polygon2d-generator#1]
Do you have any pointers on how to use this algorithm in 4.x? Currently trying to implement something similar!

**Comment by vyshliy** [comment]
You can take a look at [this](https://gitlab.com/godot_plugins/polygon2d_editor) plugin for version 4. It is slightly different in functionality, but allows you to do approximately the same thing.

**Comment by ThePat02** [comment]
> You can take a look at [this](https://gitlab.com/godot_plugins/polygon2d_editor) plugin for version 4. It is slightly different in functionality, but allows you to do approximately the same thing.

I looked at it, but it wasn't what I was looking for. Fortunately I got my implementation of automatic mesh generation to work 3 minutes ago. Your code was giving me a bit of trouble, but I got it all sorted out now! Thank you for your response!
